language: php

php:
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

notifications:
  email:
    - n.thanaphon.soo@gmail.com
    - dentistnut@gmail.com

script: phpunit

